import Header from '@/components/header';
import './globals.css'
import type { Metadata } from 'next'
import { Bellefair } from 'next/font/google'; 
import { twMerge } from 'tailwind-merge'; 

const font = Bellefair({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Space Tourism',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        

        <div className="relative min-h-screen">

        <Header />
        {children}
        </div>
        </body>
    </html>
  )
}
